version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tgbot
    environment:
      - POSTGRES_USER=urlshortner
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urlshortner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
